### ISSUE TITLE
z rotation is often viewed anticlockwise, but is described as clockwise, which is confusing

### ISSUE THREAD

**Issue by tomwang1013** [gfxfundamentals/webgl-fundamentals#193]
As follows, x & y rotation is anticlockwise, but z is clockwise(rotation angle is positive) which is opposite to what we learn from most books:
![image](https://user-images.githubusercontent.com/1826003/44825497-6b6ba780-ac3d-11e8-9f9d-bc55463638b7.png)

Is it related to the coordinate system? (if we choose right-handed or left-hand coordinate system). This great tutorial has not mention it.

**Comment by Deive-Rocky** [comment]
lol hahaha

**Comment by greggman** [comment]
😅Fixed the diagram

<img width="567" alt="Screen Shot 2020-01-15 at 12 50 03" src="https://user-images.githubusercontent.com/234804/72403509-9a80ab80-3795-11ea-9298-35c53c0cc035.png">

It's now

* x rotates down in front
* y rotates left in front
* z rotates counter clockwise

Note whether or not X is clockwise or counterclockwise depends on if you set the clock on the left or right of the cube facing the cube. Same with Y if you put the clock above the cube facing down then it will appear the opposite.

There's also the issue of camera placement. If you move the camera to the opposite side X and Z would flip

The diagram assumes no camera has been added and the projection is the normal -Z is into the screen style projection.

One other confounding thing is the article that diagram appears is making a projection with +Y down to match most 2D APIs where as +Y up is the norm for WebGL 3D.

In any case the diagram now matches

https://jsfiddle.net/greggman/Lqg93y1v/
