### ISSUE TITLE
Maybe a slight inaccuracy in amountToMoveTowardEye for "F"

### ISSUE THREAD

**Issue by NikitaIT** [gfxfundamentals/webgl-fundamentals#207]
In webgl-text-texture we take `var amountToMoveTowardEye = 150;`, but should take the distance to the opposite and not adjacent vertices.

**Comment by greggman** [comment]
you are right. The exact amount should be something like 155.88.

`amountToMoveTowardEye` is mostly just some arbitrary size. We could walk through all the the vertices of the `F` and compute the one that's the furthest away and use that (the amount above). But, if you have a really oblong object moving it so far away from the center of the object would make sure it doesn't intersect with that object but it might appear to intersect with other objects in strange ways. You can see that in the example itself.

![image](https://user-images.githubusercontent.com/234804/47978295-3f1e4c80-e100-11e8-8410-3a4fade1c4db.png)
 
Maybe I should change the comment from

    var amountToMoveTowardEye = 150;  // because the F is 150 units long

to

    var amountToMoveTowardEye = 150;  // because the furthest vertices of the F
                                      // from the origin of the F is approximately 150 units

?

**Comment by NikitaIT** [comment]
Yeah, not bad, but it is a problem, although it is obvious, it would be good to identify clearly: be prepared for the fact that labels will overlap with other objects, this can not be avoided!
