### ISSUE TITLE
"You should always set the size you want a canvas to be with CSS" is not good advice

### ISSUE THREAD

**Issue by coreyog** [gfxfundamentals/webgl-fundamentals#221]
[Link to the claim](https://webglfundamentals.org/webgl/lessons/webgl-fundamentals.html#rendering)

While following the tutorial from the very beginning I started to have issues when we get to setting the viewport.

I used CSS to specify the size of the canvas to 400x300 as the tutorial does but I wasn't using any of the helper libraries. When I was drawing the purplish-red triangle on the screen, it would display properly if I didn't use gl.viewport but as soon as I called `gl.viewport(0, 0, 400, 300)` the triangle appeared not to be drawn. It didn't matter if I hard coded 400 and 300 or if I used gl.canvas.width or gl.canvas.height.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Canvas_size_and_WebGL) the rendering size of the canvas isn't always affected by CSS. It might be different from browser to browser but Chrome on Linux behaved as this page describes.

When I called `gl.getParameter(gl.VIEWPORT)` it gave me a smaller dimension. My triangle was being draw just off screen because of the size difference. Chrome's debugger did report that the size of the canvas in the DOM was 400x300.

Specifying the width and height as properties on the canvas tag made it work.

**Comment by greggman** [comment]
I guess the article didn't do a good job of explaining.

The function `webglUtils.resizeCanvasToDisplaySize` is what makes the canvas's drawingBuffer size (the dimensions of the pixels in the canvas) match the CSS size. See https://webglfundamentals.org/webgl/lessons/webgl-resizing-the-canvas.html

So if you set the canvas's CSS to 400x300 but don't do anything else then there will be 300x150 pixels in the canvas stretched to 400x300 CSS pixels when displayed. 300x150 is the default size of the drawing buffer of the canvas and is why `gl.getParameter(gl.VIEWPORT)` returns 300x150 if you don't manually change the size of the canvas.

You should generally always set the viewport to the size of the canvas. Either

      gl.viewport(0, 0, gl.canvas.width, gl.canvas.height)

or

     gl.viewport(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight);

Again, see https://webglfundamentals.org/webgl/lessons/webgl-resizing-the-canvas.html
