### ISSUE TITLE
WebGL State Diagram: minor shader state inconsistency.

### ISSUE THREAD

**Issue by sciecode** [gfxfundamentals/webgl-fundamentals#257]
Given how the tool is made to showcase the correct WebGL state, wouldn't it be beneficial to include calls to `gl.detachShader` as well?

https://github.com/gfxfundamentals/webgl-fundamentals/blob/7240c2b132855c402d47be0acda933902021d5aa/webgl/lessons/resources/webgl-state-diagram.html#L302-L303

A lot of people don't know that the shaders are only released after they are both marked for deletion and detached from every program. This is usually not a big problem, because the shader will eventually get detached once the program is deleted, but only then the shader will be actually released.

A small comment description could go a long way to bringing more attention to this fact, and the shader panel going away, after deleting, would be correct.

**Comment by greggman** [comment]
good point, done.

**Comment by sciecode** [comment]
Nice, might also want to remove the shaders from the panel.

![image](https://user-images.githubusercontent.com/3927951/73311290-da6b7800-4204-11ea-9cb8-3adbe6044056.png)

**Comment by greggman** [comment]
That's working, you just needed to refresh or clear your cache.

**Comment by sciecode** [comment]
Indeed working, Cheers !
