### ISSUE TITLE
Simple Typo: "to up" should be "up to"

### ISSUE THREAD

**Issue by TrevinAvery** [gfxfundamentals/webgl-fundamentals#261]
Lines 37 and 38 of https://github.com/gfxfundamentals/webgl-fundamentals/blob/master/webgl/lessons/webgl-how-it-works.md state 

> That’s all very interesting but as you can see in our examples to up
> this point the fragment shader has very little info per pixel.

"to up" should be "up to"

**Comment by Iqrar99** [comment]
Nice, I'll fix the typo

**Comment by Iqrar99** [comment]
This issue can be closed now. :) Thank you
