### ISSUE TITLE
Variable duplicate declare

### ISSUE THREAD

**Issue by kagurakana** [gfxfundamentals/webgl-fundamentals#278]
At the https://webglfundamentals.org/webgl/lessons/webgl-fundamentals.html,noticed that the variable `offset` has been delclared 2 times.It's OK when using "var", but with "let",it throws error.

![](https://user-images.githubusercontent.com/37036280/83326838-a767ec80-a2a9-11ea-8f18-0252b1757333.png)

**Comment by greggman** [comment]
Yes, that is intentional. the variables are there to make the code easier to read. If you're changing the code to use `let` or `const` then you'll have to change it.

**Comment by kagurakana** [comment]
Thanks for reply, The tutorial helps me a lot, really detailed😺
