### ISSUE TITLE
About webgl-3d-perspective lesson

### ISSUE THREAD

**Issue by wlfei0502** [gfxfundamentals/webgl-fundamentals#280]
It writes  `at Z = -1 the frustum is only 1.54 units tall` .  But, I figure it out to be 1.154:

        1/tan(60°) * 2 = 1/1.732 * 2 = 1.154.

Am i wrong?

**Comment by greggman** [comment]
I think you are right. I think it's just a typo.

**Comment by greggman** [comment]
https://github.com/gfxfundamentals/webgl-fundamentals/commit/4e91b3b3b4a033dcdfb37722d2a35710edfe73b6
