### ISSUE TITLE
Maybe typo..?

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#337]
### [WebGL Precision Issues](https://webglfundamentals.org/webgl/lessons/webgl-precision-issues.html)
```
Textures are another place where the spec says the actual precision used can be greater """then""" the precision requested.
```
then -> than?

### [WebGL Matrices vs Math Matrices](https://webglfundamentals.org/webgl/lessons/webgl-matrix-vs-math.html)
```
So, when we make a 3x3 """of""" 4x4 matrix in JavaScript for WebGL we make them like this
```
of -> or?

**Comment by greggman** [comment]
yes, both of those are typos 😅

**Comment by greggman** [comment]
https://github.com/gfxfundamentals/webgl-fundamentals/commit/608b07fbbe7bb2fbd62f02bb2f63f8f095f1df00
