### ISSUE TITLE
There is no example code of Google Maps

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#341]
https://webglfundamentals.org/webgl/lessons/webgl-anti-patterns.html#properties

![image](https://user-images.githubusercontent.com/20078201/108844860-ffa50280-761f-11eb-9f60-75a4568a852d.png)

I think that needs example code of Google Maps between two sentences above.
But I cannot find some change commit about this in the last 2 years.
Am I misread something..?

**Comment by greggman** [comment]
"The example" here is not code. The example is just that, of all the webgl based websites, one of the few that handles context lost is google maps.

If it's hard to understand it would also work as

> For example, Google Maps handles webgl context lost

or

>  Most websites do not handle webgl context lost. One exception is Google Maps

The point of listing "Google Maps" is it's an important site that takes handing context lost seriously. Most webgl apps just fail and you have to reload the page.

**Comment by TroyTae** [comment]
@greggman 
Ah I see, Google Map itself was a example that handles context lost.
I confused because of this sentence(`The problem with the code above`) and new line between sentences.
Thank you :)
