### ISSUE TITLE
What's the DOSing mean?

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#342]
I searched this keyword, and top result is about medicines.

I also searched "computer science DOSing".

But there is no satisfied result.

What's this mean?

**Comment by TroyTae** [comment]
Ah I'm sorry I misread this article
Really sorry 😓

**Comment by greggman** [comment]
DOS = Denial of Service = Preventing you from using the service. For WebGL you can DOS the GPU, but doing so just means no one is going to visit your website anymore.

https://en.wikipedia.org/wiki/Denial-of-service_attack

**Comment by TroyTae** [comment]
Thank you 👍 
Looks like DDoS attack.
I add a wiki in a1369c82

**Comment by greggman** [comment]
DDoS requires a network, DoS does not.

Examples

http://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=DOS

>
