### ISSUE TITLE
How about change from filter to texture filtering

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#343]
https://webglfundamentals.org/webgl/lessons/webgl-resizing-the-canvas.html
`
Because the browser takes our 10x15 pixel canvas and stretches it to 400x300 pixels and generally it """filters""" it when it stretches it.
`

I think some people can confuse because `filter` has various of meaning.

So if the meaning you intended is `texture filtering`, how about replace it?

**Comment by greggman** [comment]
I don't know what other word to use there. "texture filtering" is the wrong word. What filtering the browser does is up to the browser. It could do lanczos filtering, it could do nearest neighbor, box filtering, hqw, waifu, it could any kind of filtering it wants.

You could change it to "interpolates" or "resamples" maybe

**Comment by TroyTae** [comment]
Is there nearest meaning in this [list](https://en.wikipedia.org/wiki/Filter)?
(I cannot find 😅)

If not, I'll change it to "interpolates" or "resamples".

**Comment by greggman** [comment]
https://www.google.com/search?q=image+filtering

**Comment by TroyTae** [comment]
Maybe this is nearest meaning, right?
https://en.wikipedia.org/wiki/Image_scaling

**Comment by greggman** [comment]
"image scaling" won't fit in the original sentence. It doesn't suggest that the way the image is scaled uses an image filtering algorithm

https://www.google.com/search?q=filtering+algorithm+for+resizing+an+image

You can see in the google results, scaling an image uses a filter. Examples

From the article you linked to from Wikipedia

>  In the case of up sampling, a reconstruction **filter** takes the place of the anti-aliasing **filter**.

From [the second article](https://scholarworks.rit.edu/cgi/viewcontent.cgi?article=10864&context=theses) from the search above

> Image Down-Scaler Using the Box **Filter** Algorithm

The [3rd result](https://www.researchgate.net/publication/258996383_Image_Filtering_and_Scaling_Algorithms)

> Image **Filtering** and Scaling Algorithms

The [4th result](http://www.ijsrp.org/research-paper-0514/ijsrp-p2934.pdf)

> An Efficient Algorithm for Image Scaling with High Boost **Filtering**

The [6th result](https://entropymine.com/imageworsener/resample/)

> How do you actually go about using such a **filter** to resize an image?

**Comment by TroyTae** [comment]
It seems `filter` has more broad meaning than I thought.

Now I understood what you said "What filtering the browser does is up to the browser."

I think this sentence explains it well. `The filter does calculate how much each source pixel contributes to each destination.` (https://stackoverflow.com/questions/12455426/image-resizing-what-is-a-filter)

And me too, I don't know what other word to use there.

The `filter` might be the best...

Anyway thank you for your explain and sorry for taking your time 😭
