### ISSUE TITLE
primitives.js implementation does not match documentation.

### ISSUE THREAD

**Issue by Scott-Coleman** [gfxfundamentals/webgl-fundamentals#345]
From the lesson, "**Drawing Multiple Things**", in the source file "**primitives.js**"...

If I understand the documentation for the "**createSphereVertices()**" function, it does not match the implementation.  

Within the function, the optional parameter "**opt_startLatitudeInRadians**" is missing from calculation of "**phi**".  

I think the line should be: 

`const phi = latRange * v + opt_startLatitudeInRadians;`

...or by some other mechanism "**opt_startLatitudeInRadians**" needs to be the starting point for calculation of "**phi**".

By inspection, a similar issue exists for the computation of "**theta**"

**Comment by greggman** [comment]
https://github.com/gfxfundamentals/webgl-fundamentals/commit/608047270e4ebd3fb322428451506c65e1031a02
