### ISSUE TITLE
Is there a reason comparing by 0.0001 instead of 0?

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#347]
```
function normalize(v) {
  var length = Math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
  // make sure we don't divide by 0.
  if (length > 0.00001) {
    return [v[0] / length, v[1] / length, v[2] / length];
  } else {
    return [0, 0, 0];
  }
}
```
Is there a reason comparing by 0.0001 instead of 0 in this code?

Is it related with range of data type?

**Comment by greggman** [comment]
I'm honestly not sure off the top of my head. This might just be left over from C++ where divide by 0 throws an exception (it doesn't in JavaScript)

There is the issue that if you're adding up normals (for example to compute a vertex normals from a mesh without), a single bad normal (divide by 0) will ruin the entire calculation.  Let's say you're trying to compute a vertex normal so it's

```
sumNormals = [0,0,0];
for each face
   norm = normalize(cross(
       normalize(subtract(facePoint1, facePoint0)),
       normalize(subtract(facePoint2, facePoint0))));
   sumNormals = add(sumNormals, norm);
}
vertexNorm = normalize(divideByScalar(sumNormals, numFaces));
```

If one face is too small or degenerate then you'll get a divide by zero which will produce `Infinity` so the vertex normal becomes `[Infinity, Infinity, Infinity]` where as with the check above the vertex normal will work even with the degenerate triangle in the data.

**Comment by TroyTae** [comment]
Oops sorry I wrote it wrong.
I wanna ask the reason that checks by 0.0001.
I understood we get Infinity when we dividing by 0.
So I thought "Isn't it enough to check 0?", Like this: `if (length > 0)`

**Comment by greggman** [comment]
It's no different than most floating point comparisons. It's generally considered bad to check for specific floating point values. 

```
if (value === 3.0)               // BAD, most floating point calculations will never be exactly 3.0
if (abs(value - 3.0) > Epsilon)  // GOOD, where Epsilon = some small value like 0.00001
```

In this case we know length is a positive value so we don't need the `abs` and I didn't name 0.00001 as `Epsilon`

**Comment by TroyTae** [comment]
Ah I understand, thank you!
