### ISSUE TITLE
Question: what does `type of thing` mean in this sentence?

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#350]
https://webglfundamentals.org/webgl/lessons/webgl-3d-lighting-spot.html

```
One is we're negating u_lightDirection above.
That's a six of one, half dozen of another type of thing. 
```

I understood `six of one, half dozen of another` means "6 = 12/2, so it's same".
Then which `type of thing` is same with `-u_lightDirection `?

**Comment by greggman** [comment]
It means "there are many ways to do it"

we can do any of these

1. `float dotFromDirection = dot(surfaceToLightDirection, -u_lightDirection);`
2. `float dotFromDirection = dot(-surfaceToLightDirection, u_lightDirection);`
3. `float dotFromDirection = 1.0 - dot(surfaceToLightDirection, u_lightDirection);`
4. `float dotFromDirection = 1.0 - dot(-surfaceToLightDirection, -u_lightDirection);`
5. `float dotFromDirection = 1.0 - dot(lightToSurfaceDirection, -u_lightDirection);`
6. `float dotFromDirection = 1.0 - dot(surfaceToLightDirection, u_inverselightDirection);`

etc...

**Comment by TroyTae** [comment]
👍
