### ISSUE TITLE
Suggestion: lerp alternative

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#351]
https://webglfundamentals.org/webgl/lessons/webgl-3d-lighting-spot.html

```
If we're between the inner limit and the outer limit then lerp between 1.0 and 0.0.
```
I found `lerp` is a Unity function that means `linear interpolation`.
So how about use `linear interpolation` instead of `lerp`?
Or in this case, I think just `clamp` also good! (https://en.wikipedia.org/wiki/Clamping_(graphics))

**Comment by greggman** [comment]
yes that's fine. It would read

> If we're between the inner limit and the outer limit then linearly interpolate between 1.0 and 0.0.

**Comment by TroyTae** [comment]
80499b2dd976c14e13def7fa4573090add0eaa18
