### ISSUE TITLE
Bug: top of F is always black

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#352]
https://webglfundamentals.org/webgl/lessons/webgl-3d-lighting-spot.html

![image](https://user-images.githubusercontent.com/20078201/114203297-fd5df400-9992-11eb-9f5d-edd7ae67f717.png)

The top of F is always black.
Is this intended?

**Comment by greggman** [comment]
That is not a bug. The spot light is below the top of the F

![light](https://user-images.githubusercontent.com/234804/114264087-d69bce00-9a23-11eb-9e6a-555c19915565.png)

If you move the light above the top of the F then it will project light

https://jsgist.org/?src=088442a351f57517210475f9c9b2d535

**Comment by TroyTae** [comment]
Ah I see, thank you!
