### ISSUE TITLE
Question: nuance of FTW

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#356]
![image](https://user-images.githubusercontent.com/20078201/116874335-24d37400-ac54-11eb-92db-d690c3aaa0c9.png)

```
Programmer art and programmer animation FTW!  :P
```
I found FTW means `for the win`.
But I cannot understand nuance of FTW in this context:

1. Here's a block guy
2. It's using TRS source
3. For the win! (???)

Is it a famouse dance for victory..?

**Comment by greggman** [comment]
"programmer art" = "ugly art" because a programmer is usually not an artist. So I guess it means "sorry for the bad art and animation" by saying the opposite "see this amazing art and animation, haha"

**Comment by TroyTae** [comment]
It was a self-inflicted joke.
Thank you!
