### ISSUE TITLE
Question: Isn't it same with `1` regardless of `t`?

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#360]
https://webglfundamentals.org/webgl/lessons/webgl-3d-perspective-correct-texturemapping.html

![image](https://user-images.githubusercontent.com/20078201/119397246-cf4d2d00-bd10-11eb-8c12-71d9bc37705a.png)

```
(1 - t) + t when t goes from 0 to 1 is the same as 1. 
```

It seems to be 1 regardless of the value of `t`.

Because we can combine equation above like this:

```
(1 - t) + t
```
```
1 - t + t
```
```
1
```

I think we can remove this part(`when t goes from 0 to 1`).

**Comment by greggman** [comment]
I agree, your explanation is better.
