### ISSUE TITLE
WebGL1/2 Fundamentals Synchronization

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#366]
How are you doing the synchronization of WebGL1/2 Fundamentals now?

Most of articles are same, but it seems there is no synchronization system.

So I can see that some contributor made translation which already complete in webgl1.

**Comment by greggman** [comment]
there is no synchronisation system. the articles look the same but there are too many small differences to do anything automatically

**Comment by TroyTae** [comment]
Oops there are some small differences between 1/2.
Then.. how about to add a guide in translating of README.md?
(e.g. It may have been already translated in 1(or 2), so please refer that before translating)

**Comment by TroyTae** [comment]
First of all, I'll have to sync 1/2 in this weekend for korean contributor 😅

**Comment by greggman** [comment]
the differences are not always small but yes, it's not a bad idea to
reference the other translation.
