### ISSUE TITLE
Duplicate gl.bindBuffer in webgl-fundamentals.html?

### ISSUE THREAD

**Issue by gaopinghuang0** [gfxfundamentals/webgl-fundamentals#369]
In [webgl-fundamentals.html](https://github.com/gfxfundamentals/webgl-fundamentals/blob/master/webgl/webgl-fundamentals.html),

```js
function main() {

  // Bind it to ARRAY_BUFFER (think of it as ARRAY_BUFFER = positionBuffer)
  gl.bindBuffer(gl.ARRAY_BUFFER, positionBuffer);

...

  // Bind the position buffer.
  gl.bindBuffer(gl.ARRAY_BUFFER, positionBuffer);

}
```
It seems that Line 107 and line 135 are duplicate.

**Comment by greggman** [comment]
You are not alone in noticing that [https://webglfundamentals.org/webgl/lessons/webgl-fundamentals.html#comment-4238783504](1), [https://webglfundamentals.org/webgl/lessons/webgl-fundamentals.html#comment-3268327726](2).

Typically you draw multiple things, so you'd have to do

```
gl.bindBuffer(..., bufferForThing1);
// put data in for thing1
...
gl.bindBuffer(..., bufferForThing2);
// put data in for thing2
```

Then at draw time you'd need to bind each buffer to draw each thing

```
gl.bindBuffer(..., bufferForThing1);
// draw thing1
...
gl.bindBuffer(..., bufferForThing2);
// draw thing2
```

So the code follows that pattern. It just happens to draw one thing. It's not common to draw only one thing though.
