### ISSUE TITLE
Is the example lost?

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#374]
https://webglfundamentals.org/webgl/lessons/webgl-3d-geometry-lathe.html
![image](https://user-images.githubusercontent.com/20078201/134511521-6d3112ce-c5eb-4ec3-aa38-c515dbbb0ed9.png)
```
If you slide the sliders for the most vertices you can generate ~20000 vertices.
```
In this article, you suggest to test with slider of maximum vertices.
But I have no idea what slider you mean.
Is some example lost in here?

**Comment by greggman** [comment]
I can see it's unclear as written. Sorry. The point is if you go to any of the examples and set the distance slider to say 0.001 and the divisions slider to 60 you'll get 114k vertices (not sure where the 20k value came from). An O^2 solution on 114k is 12 billion operations. There's no example to run, only an explanation of how I solved the seam and why my first solution was too slow.

Feel free to rewrite it.

**Comment by greggman** [comment]
To be defensive, it's not wrong as is. 

> If you slide the sliders for the most vertices you can generate ~20000 vertices.

Means some of the sliders affect how many vertices are generated. If you slide those sliders such that they generate lots of vertices they'll generate ~20000 vertices. 

It should probably say >20000 vertices, or change to > 114000 vertices (or 114k vertices).  But specifying specifically the distance and divisions sliders would be more clear.

**Comment by TroyTae** [comment]
@greggman 
Thank you!
I change like this: 07a5a354e
Please notice me if I changed wrong :)
