### ISSUE TITLE
WebGL Using 2 or More Textures (wrong order of calls)

### ISSUE THREAD

**Issue by Aiosa** [gfxfundamentals/webgl-fundamentals#377]
In the article about [using multiple textures](https://webglfundamentals.org/webgl/lessons/webgl-2-textures.html) the initial example is at least very confusing:

"Then we have to bind a texture to each of those texture units."

And probably also wrong. I could not get it running until I read the 'how would you implement it in javascript' part.

At the beginning  you are using 'gl.texImage2D' without specifying active texture unit, which is done at the very bottom of the initial example -- but you need to first set active unit in order to load the data. Please, fix it.

**Comment by greggman** [comment]
I'm sorry you found it confusing. There's no need to specify an active texture unit at the beginning. Creating textures and putting data in them and setting their parameters is entirely unrelated to using them at render time.

There are only 8 to 32 texture units (depending on your GPU). They are how you tell a shader which textures to use. Separately you can have 1000s of textures, way more than active texture units. 

Before rendering something (before calling gl.drawArrays or gl.drawElements) you need set up the texture units to point to the texture used used for that draw call.

**Comment by greggman** [comment]
One more example based on my comment above. Imagine we have code to make 8 textures

```
function makeTexture(gl, color) {
  const tex = gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D, tex);
  gl.texImage2D(gl.TEXUTRE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, new Uint8Array(color));
  return tex;
}

const textures = {
   red: makeTexture(gl, [255, 0, 0, 255]),
   yellow: makeTexture(gl, [255, 255, 0, 255]),
   green: makeTexture(gl, [0, 255, 0, 255]),
   cyan: makeTexture(gl, [0, 255, 255, 255]),
   blue: makeTexture(gl, [0, 0, 255, 255]),
   magenta: makeTexture(gl, [255, 0, 255, 255]),
   black: makeTexture(gl, [0, 0, 0, 255]),
   white: makeTexture(gl, [255, 255, 255, 255]),
};
```

Then at render time we can any texture on any texture unit. We just need to tell our shader which texture units we bound our textures to. Just to be random let's use texture units 3 and 7

```
// --- [draw something]---
gl.activeTexture(gl.TEXTURE3);
gl.bindTexture(gl.TEXTURE_2D, textures.blue);   // put blue on unit 3
gl.activeTexture(gl.TEXTURE7);
gl.bindTexture(gl.TEXTURE_2D, textures.yellow);   // put yellow on unit 7

gl.uniform1i(someUniformSamplerLocation, 3);   // tell the shader to use unit 3 for this uniform sampler
gl.uniform1i(someOtherUniformSamplerLocation, 7);   // tell the shader to use unit 7 for this uniform sampler

gl.drawArrays(....);

// --- [draw something else]---
gl.activeTexture(gl.TEXTURE3);
gl.bindTexture(gl.TEXTURE_2D, textures.cyan);   // put cyan on unit 3
gl.activeTexture(gl.TEXTURE7);
gl.bindTexture(gl.TEXTURE_2D, textures.magenta);   // put magent on unit 7

gl.uniform1i(someUniformSamplerLocation, 3);   // tell the shader to use unit 3 for this uniform sampler
gl.uniform1i(someOtherUniformSamplerLocation, 7);   // tell the shader to use unit 7 for this uniform sampler

gl.drawArrays(....);

// Use different texture units just for the heck of it
gl.activeTexture(gl.TEXTURE6);
gl.bindTexture(gl.TEXTURE_2D, textures.white);   // put white on unit 6
gl.activeTexture(gl.TEXTURE2);
gl.bindTexture(gl.TEXTURE_2D, textures.red);   // put red on unit 2

gl.uniform1i(someUniformSamplerLocation, 6);   // tell the shader to use unit 6 for this uniform sampler
gl.uniform1i(someOtherUniformSamplerLocation, 2);   // tell the shader to use unit 2 for this uniform sampler

gl.drawArrays(....);
...

you might find [this](https://webglfundamentals.org/webgl/lessons/resources/webgl-state-diagram.html) helpful

**Comment by Aiosa** [comment]
Well, this is something I was pointing out: I might be wrong but following the `javascript implementation` example,  calling `texImage2D` will upload the data to `TEXTURE0` so the for loop will populate with data only the first texture unit.

I do understand that `bindTexture` should specify to which texture am I uploading the data, yet until I started specifying the actual texture unit before calling `texImage2D` it did not work.

The `javascript implementation` uses 
>var activeTexture = function(unit) {
function to set up active unit and 
>var texImage2D = function(target, ... args ...) {
uses the location of `activeTexture`  as where to load the data

So either of these examples in the tutorial should be wrong...

**Comment by greggman** [comment]
> yet until I started specifying the actual texture unit before calling texImage2D it did not work.

You should post your code

> So either of these examples (the code you showed above and the demo javascript OpenGL api implementation) in the tutorial should be wrong...

The samples are not wrong

"Texture Units" are not "Textures". Texture Units are just a global array of references to textures. When setting up a texture which texture unit is active is mostly irrelevant. What's relevant is what they are when you call `gl.drawArrays` or `gl.drawElements`

In the code, after the first iteration of the loading loop the state will be like this 

<img width="573" alt="Screen Shot 2021-11-26 at 13 02 54" src="https://user-images.githubusercontent.com/234804/143647374-65a45111-6bab-4c50-8861-cd2f650013c2.png">

After the second iteration of the loading loop the state will be like this

<img width="613" alt="Screen Shot 2021-11-26 at 13 03 11" src="https://user-images.githubusercontent.com/234804/143647623-5648e91e-0c32-4f8e-8303-c7fad4c689f1.png">

After the setup in the rendering part of the code, just before calling `gl.drawArrays` the state will be like this

<img width="599" alt="Screen Shot 2021-11-26 at 13 04 01" src="https://user-images.githubusercontent.com/234804/143648699-76345053-bcbe-4557-94ef-db3b1e677710.png">

>  I am already kind of advanced OpenGL user 

Me too 😉  I wrote the WebGL implementation in both Chrome and WebKit, I wrote the GPU infrastructure in Chrome including an entire OpenGL ES driver, and I wrote the majority of the WebGL1 Conformance Tests 😉

**Comment by Aiosa** [comment]
Ah, I see. I did not read the whole thing and it re-uses the spot for different pointers.

```
 let _this = this,
 index = 0;
 const NUM_IMAGES = Math.round(image.height / tileBounds.height);
 //images are sent below each other, it can be passed at once into IMAGE_ARRAY, this is inside WebGL 1.0 strategy fallback
 this.canvas.width = image.width;
 this.canvas.height = image.height;
 this.canvasReader.drawImage(image, 0, 0);

 //the logic of not running out of tex units is somewhere else
 for (let key in visualisation.shaders) {
         let layer = visualisation.shaders[key];
         this._units.push(gl.createTexture());
                  
         let bindConst = `TEXTURE${index}`;
         gl.activeTexture(gl[bindConst]);  //started working only after calling it now
         let location = gl.getUniformLocation(program, `data_${layer.order}`);
         gl.uniform1i(location, index);  // texture unit 0

         gl.bindTexture(gl.TEXTURE_2D, this._units[index]);
         //some params
         gl.texParameteri(...);

         let read = this.canvasReader.getImageData(0, layer.order*tileBounds.height, tileBounds.width, tileBounds.height);
         let pixels = new Uint8Array(read.data.buffer);
         gl.texImage2D(gl.TEXTURE_2D,
                        0,
                        gl.RGBA,
                        tileBounds.width,
                        tileBounds.height,
                        0,
                        gl.RGBA,
                        gl.UNSIGNED_BYTE,
                        pixels);
         //preivously, the code has been here (followng the example):
         // gl.activeTexture(gl[bindConst]);
         // gl.bindTexture(gl.TEXTURE_2D, this._units[index]);

         index++;
}

```

So I do get what changed - I am reusing multiple spaces to load my data into textures and since I immediately use it actually saves me some API calls. However, why it was not working before leaves me clueless.

Offtopic: I was also wondering what about memory management: when do you _DELETE_ textures? Almost nowhere is an example of how (or rather: when) to clean up after yourself. Is it ok to leave it just like that and all will be freed when the GC collects the canvas?

Thank you.

**Comment by greggman** [comment]
Comment on the code:

You don't need to make strings for GL constants. There's nothing special about the constants in WebGL. These are all the same

```
gl.activeTexture(gl[`TEXTURE${index}`]);
gl.activeTexture(gl.TEXUTRE0 + index]);
gl.activeTexture(33984 + index);
```

Of course maybe you were making a string because you wanted to print it somewhere else. That's fine. Just pointing out you don't need to use the actual properties on the WebGLRenderingContext (`gl`). They're just numbers, they don't change. 

As for deleting you should delete WebGL objects yourself. Yes, they will eventually get garbage collected but the problem is JavaScript doesn't know anything about the memory used for textures (or other WebGL objects). As far as it's concerned a texture is just some tiny tracking object to some opaque thing. JavaScript doesn't know how much VRAM there is, nor does it know that freeing these opaque texture tracking objects will free up VRAM when VRAM is full.

So, free (delete) webgl objects when you no longer need them.

I'd say the majority of WebGL apps (which are mostly visualizations like the ones [here](https://threejs.org)) never free anything because they just load the stuff they need and use all of it until the page is closed. For apps that do more though, like a photo editor, they would need to do more and delete things themselves.
