### ISSUE TITLE
possible bug in m3.js

### ISSUE THREAD

**Issue by MaudDibb** [gfxfundamentals/webgl-fundamentals#390]
in m3.js, the inverse function:

    const m00 = m[0 * 4 + 0];
    const m01 = m[0 * 4 + 1];
    const m02 = m[0 * 4 + 2];
    const m10 = m[1 * 4 + 0];
    const m11 = m[1 * 4 + 1];
    const m12 = m[1 * 4 + 2];
    const m20 = m[2 * 4 + 0];
    const m21 = m[2 * 4 + 1];
    const m22 = m[2 * 4 + 2];

should those  4's  be  3's  instead? you\re working with 3x3 matrices, not 4x4

**Comment by jan-ale** [comment]
why isn't this closed?
