### ISSUE TITLE
error in textures example code

### ISSUE THREAD

**Issue by TheJunglePedantic** [gfxfundamentals/webgl-fundamentals#392]
in the third chunk of example code at https://webglfundamentals.org/webgl/lessons/webgl-3d-textures.html 

<pre><code>
// look up where the vertex data needs to go.
var positionLocation = gl.getAttribLocation(program, "a_position");
var texcoordLocation = gl.getAttribLocation(program, "a_texcoords");
 
...
 
// Create a buffer for texcoords.
var buffer = gl.createBuffer();
gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
gl.enableVertexAttribArray(texcoordLocation);
 
// We'll supply texcoords as floats.
gl.vertexAttribPointer(texcoordLocation, 2, gl.FLOAT, false, 0, 0);
 
// Set Texcoords.
setTexcoords(gl);
</code></pre>

on the third line a_texcoords should be a_texcoord to match the shader earlier in the page. In the running example it is fixed.

**Comment by greggman** [comment]
thanks!

https://github.com/gfxfundamentals/webgl-fundamentals/commit/63b55d84bd6a96c166fbd042cf7ec33961d1904a

**Comment by TheJunglePedantic** [comment]
thank you!!
