### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by alicialics** [gfxfundamentals/webgl-fundamentals#414]
The tinypic links in this file are broken.

https://github.com/gfxfundamentals/webgl-fundamentals/blob/master/webgl/lessons/webgl-qna-how-to-make-webgl-canvas-transparent.md

**Comment by greggman** [comment]
thanks. fixed

https://github.com/gfxfundamentals/webgl-fundamentals/commit/23f9872c5752bbf0b404aed8e022b4474460c0b4
