### ISSUE TITLE
webgl-state-diagram: extraneous column heading in vertex array

### ISSUE THREAD

**Issue by thatmichaelpark** [gfxfundamentals/webgl-fundamentals#422]
![Screenshot 2023-03-01 at 1 48 59 PM](https://user-images.githubusercontent.com/16363045/222272956-52f3b33d-a150-4017-a234-f7b24ad1fecf.png)

**Comment by thatmichaelpark** [comment]
Awesome learning aid btw!

**Comment by greggman** [comment]
Thanks. Fixed
