### ISSUE TITLE
Broken link in Load Obj

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#423]
It seems this link(https://users.cs.utah.edu/~boulos/cs3505/obj_spec.pdf) is no longer valid
This link is used twice in [this article](https://webglfundamentals.org/webgl/lessons/webgl-load-obj.html)

**Comment by greggman** [comment]
thanks

fixed  https://github.com/gfxfundamentals/webgl-fundamentals/commit/c3a8e1ab7982e8cde80ca256736f7ea7e7abb608
